### ISSUE TITLE
No need to wait for data after Wire.requestFrom()

### ISSUE THREAD

**Issue by Koepel** [sparkfun/Infrared_Proximity_Breakout-VCNL4000#1]
There is no need to wait for data after the call to Wire.requestFrom().
When the function Wire.requestFrom() returns, the I2C transaction has completely finished and the received data is waiting in the buffer in the Wire library.

**Comment by bboyho** [comment]
Hi,

Sorry for the delay in reply. I was browsing some issues when I noticed this issue that was filed. When the code was originally written, I don't believe that we were aware of the [common mistakes that came with using the Wire library](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#1).

I have [removed the line](https://github.com/sparkfun/Infrared_Proximity_Breakout-VCNL4000/commit/90bc6496469964f7fe3b7638f1a1f328e87f960d).
